name: Download
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
       DEBIAN_FRONTEND: noninteractive
      run: |
       sudo timedatectl set-timezone "$TZ"

    - name: Clone Sources
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       git config --global user.name 'ZarkZero'
       git config --global user.email '782558181@qq.com'
       git clone https://github.com/ZarkZero/test3.git
       git clone https://github.com/Boos4721/openwrt.git
       cd openwrt
       git remote add origin2 https://github.com/Boos4721/openwrt.git
       git checkout 95a85b4247
       git pull --rebase origin2 master
       cp -rf target/linux/ipq807x ../test3
       cd ..
 
    - name: Upload Sources
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       cd test3
       git add .
       git commit -m "first commit"
       git push -u origin main      
