name: Download
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
       token: ${{ secrets.PAT }}

    - name: Initialization environment
      env:
       DEBIAN_FRONTEND: noninteractive
      run: |
       sudo timedatectl set-timezone "$TZ"

    - name: Clone Sources
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       git config --global user.name 'ZarkZero'
       git config --global user.email '782558181@qq.com'
       git config global --add url."git@github.com:".insteadOf "https://github.com/"
       git clone https://github.com/ZarkZero/test3.git
       git clone https://github.com/Boos4721/openwrt.git
       cd openwrt
       git remote add origin2 https://github.com/Boos4721/openwrt.git
       git checkout 95a85b4247
       git pull --rebase origin2 master
       cp -rf target/linux/ipq807x ../test3
       cd ../test3
       
    - name: Upload Sources
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       cd test3
       git add .
       git commit -m "first commit"
       git remote add origin2 https://ZarkZero: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@github.com/ZarkZero/test3
       git push -u origin2 main
